version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    environment:
      MY_VAL: some-val
    steps:
      - checkout
      - run:
          name: echo val
          command: echo $MY_VAL
workflows:
  version: 2
  one:
    jobs:
      - one
